executable              = CARLRun.sh
arguments               = $(ClusterId)$(ProcId)
output                  = CARLRun.$(ClusterId).$(ProcId).out
error                   = CARLRun.$(ClusterId).$(ProcId).err
log                     = CARLRun.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = carl-torch.tar.gz
when_to_transfer_output = ON_EXIT
+JobFlavour             = longlunch
request_GPUs = 1
request_CPUs = 0
queue
